export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const CLEAR_AUTH = "CLEAR_AUTH";
export const TICKETS_ADDED = "TICKETS_ADDED";
export const PRIZES_LOADED = "PRIZES_LOADED";
export const CLEAR_PRIZES = "CLEAR_PRIZES";
export const PRIZE_SUCCESS = "PRIZE_SUCCESS";
export const PRIZE_FAIL = "PRIZE_FAIL";
export const ENTER_SUCCESS_PRIZE = "ENTER_SUCCESS_PRIZE";
export const ENTER_SUCCESS_USER = "ENTER_SUCCESS_USER";
export const CHARITIES_LOADED = "CHARITIES_LOADED";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const SHOW_CHARITY_MODAL = "SHOW_CHARITY_MODAL";
export const HIDE_CHARITY_MODAL = "HIDE_CHARITY_MODAL";

export const SHOW_CONFIRM_MODAL = "SHOW_CONFIRM_MODAL";
export const HIDE_CONFIRM_MODAL = "HIDE_CONFIRM_MODAL";

export const USER_PLEDGE_SUCCESS = "USER_PLEDGE_SUCCESS";
export const PRIZE_PLEDGE_SUCCESS = "PRIZE_PLEDGE_SUCCESS";

export const START_LOADER = "START_LOADER";
export const END_LOADER = "END_LOADER";

export const LOAD_RESULT = "LOAD_RESULT";
